# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Finance with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

### NumPy is already included in your environment! You are good to go if you are using pyfinance env!

_____
##### For those not using the provided environment:

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

_____

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
type(my_list)

list

In [7]:
type(np.array(my_list))

numpy.ndarray

In [20]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
np.ones((3,1))

array([[ 1.],
       [ 1.],
       [ 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [29]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [16]:
np.linspace(1,10,30)#evenly spaced

array([  1.        ,   1.31034483,   1.62068966,   1.93103448,
         2.24137931,   2.55172414,   2.86206897,   3.17241379,
         3.48275862,   3.79310345,   4.10344828,   4.4137931 ,
         4.72413793,   5.03448276,   5.34482759,   5.65517241,
         5.96551724,   6.27586207,   6.5862069 ,   6.89655172,
         7.20689655,   7.51724138,   7.82758621,   8.13793103,
         8.44827586,   8.75862069,   9.06896552,   9.37931034,
         9.68965517,  10.        ])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [23]:
#uniform distribution
np.random.rand(1)#one number between 0 and 1

array([ 0.12631626])

In [22]:
np.random.rand(2)

array([ 0.67156835,  0.11105188])

In [25]:
np.random.rand(5,5)

array([[ 0.88561506,  0.63671116,  0.45348572,  0.78339065,  0.09258263],
       [ 0.24092948,  0.68510714,  0.58329302,  0.26724089,  0.412023  ],
       [ 0.7120278 ,  0.84909489,  0.77380892,  0.26402355,  0.40306258],
       [ 0.02935024,  0.88535722,  0.11614607,  0.51057581,  0.69162114],
       [ 0.29772813,  0.02921989,  0.09810401,  0.01052092,  0.28210178]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [27]:
#normal distribution
np.random.randn(5)#five number from 1 to 0,from standard distribution

array([ 0.6457791 ,  0.13965733,  0.88834656,  0.67370368, -0.62479924])

In [28]:
np.random.randn(5,5)

array([[ 0.85713501,  2.59675502,  0.86668345, -0.48519948, -1.02650516],
       [ 0.12000069, -0.09184971,  0.02313599, -0.79527669, -1.7334041 ],
       [-1.58307307,  0.29509094, -2.78116671,  0.09867868, -0.20809483],
       [-1.86533889,  1.12267483,  0.79587913, -0.07956112, -0.69069242],
       [ 0.06617531,  1.57182879,  0.52366182,  0.06438111,  0.49383085]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [31]:
np.random.randint(3,100)

67

In [32]:
np.random.randint(1,100,10)#you can difine the range

array([52, 10,  1,  5, 61, 27, 65, 17, 50, 79])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [33]:
arr = np.arange(25)# constant array 
ranarr = np.random.randint(0,50,10)#random array

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.

In [41]:
arr.reshape(1,25)#only matix can be reshaped

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
arr.reshape(1,25).shape

(1, 25)

In [48]:
n=arr.reshape(1,25)
n.shape

(1, 25)

In [42]:
arr.shape

(25,)

In [43]:
arr.reshape(5,5)# one dimentional array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape(5,5).shape

(5, 5)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [49]:
ranarr

array([44, 23, 48, 34, 17,  7, 47, 11, 20, 33])

In [50]:
ranarr.max()

48

In [54]:
ranarr.argmax()#find the index max lies

2

In [52]:
ranarr.min()

7

In [53]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

dtype('int64')

# Great Job!